package dev.artixdev.libs.com.github.retrooper.packetevents.protocol.packettype.serverbound;

public enum ServerboundPacketType_1_7_10 {
   KEEP_ALIVE,
   CHAT_MESSAGE,
   INTERACT_ENTITY,
   PLAYER_FLYING,
   PLAYER_POSITION,
   PLAYER_ROTATION,
   PLAYER_POSITION_AND_ROTATION,
   PLAYER_DIGGING,
   PLAYER_BLOCK_PLACEMENT,
   HELD_ITEM_CHANGE,
   ANIMATION,
   ENTITY_ACTION,
   STEER_VEHICLE,
   CLOSE_WINDOW,
   CLICK_WINDOW,
   WINDOW_CONFIRMATION,
   CREATIVE_INVENTORY_ACTION,
   CLICK_WINDOW_BUTTON,
   UPDATE_SIGN,
   PLAYER_ABILITIES,
   TAB_COMPLETE,
   CLIENT_SETTINGS,
   CLIENT_STATUS,
   PLUGIN_MESSAGE;

   // $FF: synthetic method
   private static ServerboundPacketType_1_7_10[] $values() {
      return new ServerboundPacketType_1_7_10[]{KEEP_ALIVE, CHAT_MESSAGE, INTERACT_ENTITY, PLAYER_FLYING, PLAYER_POSITION, PLAYER_ROTATION, PLAYER_POSITION_AND_ROTATION, PLAYER_DIGGING, PLAYER_BLOCK_PLACEMENT, HELD_ITEM_CHANGE, ANIMATION, ENTITY_ACTION, STEER_VEHICLE, CLOSE_WINDOW, CLICK_WINDOW, WINDOW_CONFIRMATION, CREATIVE_INVENTORY_ACTION, CLICK_WINDOW_BUTTON, UPDATE_SIGN, PLAYER_ABILITIES, TAB_COMPLETE, CLIENT_SETTINGS, CLIENT_STATUS, PLUGIN_MESSAGE};
   }
}
