package dev.artixdev.libs.com.github.retrooper.packetevents.protocol.packettype.serverbound;

public enum ServerboundPacketType_1_9 {
   TELEPORT_CONFIRM,
   TAB_COMPLETE,
   CHAT_MESSAGE,
   CLIENT_STATUS,
   CLIENT_SETTINGS,
   WINDOW_CONFIRMATION,
   CLICK_WINDOW_BUTTON,
   CLICK_WINDOW,
   CLOSE_WINDOW,
   PLUGIN_MESSAGE,
   INTERACT_ENTITY,
   KEEP_ALIVE,
   PLAYER_POSITION,
   PLAYER_POSITION_AND_ROTATION,
   PLAYER_ROTATION,
   PLAYER_FLYING,
   VEHICLE_MOVE,
   STEER_BOAT,
   PLAYER_ABILITIES,
   PLAYER_DIGGING,
   ENTITY_ACTION,
   STEER_VEHICLE,
   RESOURCE_PACK_STATUS,
   HELD_ITEM_CHANGE,
   CREATIVE_INVENTORY_ACTION,
   UPDATE_SIGN,
   ANIMATION,
   SPECTATE,
   PLAYER_BLOCK_PLACEMENT,
   USE_ITEM;

   // $FF: synthetic method
   private static ServerboundPacketType_1_9[] $values() {
      return new ServerboundPacketType_1_9[]{TELEPORT_CONFIRM, TAB_COMPLETE, CHAT_MESSAGE, CLIENT_STATUS, CLIENT_SETTINGS, WINDOW_CONFIRMATION, CLICK_WINDOW_BUTTON, CLICK_WINDOW, CLOSE_WINDOW, PLUGIN_MESSAGE, INTERACT_ENTITY, KEEP_ALIVE, PLAYER_POSITION, PLAYER_POSITION_AND_ROTATION, PLAYER_ROTATION, PLAYER_FLYING, VEHICLE_MOVE, STEER_BOAT, PLAYER_ABILITIES, PLAYER_DIGGING, ENTITY_ACTION, STEER_VEHICLE, RESOURCE_PACK_STATUS, HELD_ITEM_CHANGE, CREATIVE_INVENTORY_ACTION, UPDATE_SIGN, ANIMATION, SPECTATE, PLAYER_BLOCK_PLACEMENT, USE_ITEM};
   }
}
