#############################################################
#                                                           #
#  Articos Revamped | Versão exclusiva do Plugin conhecido  #
#  Recuse imitações, Adquira o melhor de todos em nosso...  #
#  Discord logo abaixo, está versão é exclusiva do Yulgar   #
#                                                           #
#       YULGAR | COMPETITIVE NETWORK [1.7x - 1.8.9]         #
#      IP: yulgar.com.br | LOJA: loja.yulgar.com.br         #
#                                                           #
#        ArtixDevelopment • Melhor Loja de Plugins          #
#                                                           #
#    Discord: https://discord.gg/yqK5wyPPV6 | @Faastyzin    #
#                                                           #
#############################################################

Faastyzin:
  Link: "FaastyzinTheBestDEV"

NAME-TAGS:
  PREFIX: "&#ff0000[Yulgar] "
  SUFFIX: " &9[Gay]"